enigmatry/entry-angular-building-blocks

projects/stylelint-config/index.js

rule scss/function-no-unknown, ignore functions for mat theming.

Add ignore pattern for mat theming.

---

.gitignore
.vscode/settings.json
projects/scss-foundation/.stylelintrc.json
projects/scss-foundation/dist/scss-foundation-modules.css.map
projects/scss-foundation/dist/scss-foundation.css.map
projects/scss-foundation/docs/absolute-positioning.md
projects/scss-foundation/package-lock.json
projects/scss-foundation/package.json
projects/scss-foundation/src/modules/_variables.scss
projects/scss-foundation/src/modules/layout/_grid.scss
projects/scss-foundation/src/modules/position/_set-position.scss
projects/scss-foundation/src/modules/responsiveness/_breakpoints.scss
projects/scss-foundation/src/partials/states/_visibility.scss
projects/scss-foundation/tests/position/absolute.tests.scss
projects/scss-foundation/tests/position/fixed.tests.scss
projects/scss-foundation/tests/position/set-position.tests.scss
projects/scss-foundation/tests/shim.test.js

Bumped all library versions.

---

projects/scss-foundation/src/modules/position/_set-position.scss

https://jira.enigmatry.com/browse/ETL-471

ETL-471: Revert changes on set-position mixin

---

projects/scss-foundation/.stylelintrc.json
projects/scss-foundation/package.json
projects/scss-foundation/src/modules/_variables.scss
projects/scss-foundation/src/modules/layout/_grid-core.scss
projects/scss-foundation/src/modules/layout/_grid.scss
projects/scss-foundation/src/modules/responsiveness/_breakpoints.scss
projects/scss-foundation/src/modules/text/_modification.scss
projects/scss-foundation/tests/layout/grid-core.tests.scss
projects/scss-foundation/tests/layout/grid.tests.scss
projects/scss-foundation/tests/text/modification.tests.scss

Marta's work + I did her unfinished reworks + some code clean ups.

Added grid tests. Code clean up.

---

package-lock.json
package.json
projects/entry-form/package.json
projects/entry-form/src/lib/components/ckeditor/formly-ckeditor.component.html
projects/entry-form/src/lib/components/ckeditor/formly-ckeditor.component.ts
projects/entry-form/src/lib/components/ckeditor/formly-ckeditor.module.ts
projects/entry-form/src/lib/components/formly-components.module.ts
projects/entry-form/src/lib/entry-form.module.ts
projects/entry-form/src/lib/interfaces/ckeditor-build-token.ts
projects/entry-form/src/lib/interfaces/index.ts

As a user I want to have input type with HTML editor so that I can incorporate it in my site

BP-493: Add ckeditor formly component.

---

projects/entry-table/src/styles/modules/components/tables/entry-table-nested/cells/_general.scss
projects/entry-table/src/styles/modules/themings/_default-theming.scss
projects/entry-table/src/styles/partials/core/components/tables/_cells.scss

https://jira.enigmatry.com/browse/ETL-474

ETL-474: Make min-width cell flexible 

---

projects/entry-form/src/styles/modules/components/forms/checkboxs/_general.scss
projects/entry-form/src/styles/modules/themings/_default-theming.scss
projects/entry-table/src/styles/modules/components/tables/entry-table-nested/rows/_general.scss
projects/entry-table/src/styles/modules/themings/_default-theming.scss

https://jira.enigmatry.com/browse/ETL-475

ETL-475: Check box update

---

projects/scss-foundation/README.md
projects/scss-foundation/docs/fixed-positioning.md
projects/scss-foundation/src/partials/core/_index.scss
projects/scss-foundation/src/partials/core/states/_cursors.scss
projects/scss-foundation/src/partials/core/states/_index.scss
projects/scss-foundation/src/partials/core/states/_resize.scss
projects/scss-foundation/src/partials/core/states/_visibility.scss

https://jira.enigmatry.com/browse/BP-496

BP-496: Scss Foundation documentation is outdated

---

deploy-demo.yml

Pipeline for deploying demo app to Azure Static website

Deploy demo

---

docs/src/app/examples/dialog/custom/custom-dialog.component.html
docs/src/app/examples/dialog/custom/custom-dialog.component.ts
projects/entry-components/dialog/README.md
projects/entry-components/dialog/dialogs/alert/entry-alert-dialog-data.interface.ts
projects/entry-components/dialog/dialogs/alert/entry-alert-dialog.component.html
projects/entry-components/dialog/dialogs/alert/entry-alert-dialog.component.ts
projects/entry-components/dialog/dialogs/confirm/entry-confirm-dialog-data.interface.ts
projects/entry-components/dialog/dialogs/confirm/entry-confirm-dialog.component.html
projects/entry-components/dialog/dialogs/confirm/entry-confirm-dialog.component.ts
projects/entry-components/dialog/dialogs/entry-dialog.component.html
projects/entry-components/dialog/dialogs/entry-dialog.component.ts
projects/entry-components/dialog/entry-dialog-buttons-config.interface.ts
projects/entry-components/dialog/entry-dialog-config.model.ts
projects/entry-components/dialog/entry-dialog.service.ts
projects/entry-components/dialog/public-api.ts

Update entry-dialog-config with hideClose & disableClose options;
Remove entry-dialog-buttons-config interface;

BP-441: Update entry-dialog-config with hideClose & disableClose options; remove entry-dialog-buttons-config interface;

---

angular.json
docs/src/app/shared/markdown-viewer/markdown-viewer.component.html
docs/src/styles/partial/main.scss
package-lock.json
package.json

integrate github-markdown-css package

BP-540 add markdown styles

---

angular.json
docs/src/staticwebapp.config.json

Added static web app configuration

Added static web app configuration

---

projects/scss-foundation/README.md
projects/scss-foundation/docs/absolute-positioning.md
projects/scss-foundation/docs/alignment.md
projects/scss-foundation/docs/background-hover.md
projects/scss-foundation/docs/border-radius.md
projects/scss-foundation/docs/breakpoints.md
projects/scss-foundation/docs/fixed-positioning.md
projects/scss-foundation/docs/row-coloring.md
projects/scss-foundation/docs/text-hover.md
projects/scss-foundation/docs/text-modification.md
projects/scss-foundation/src/modules/states/_hover.scss
projects/scss-foundation/src/modules/states/_index.scss

https://jira.enigmatry.com/browse/BP-555

BP-555: Add background hover mixin and docs

---

libs/scss-entry/src/modules/elements/buttons/_default.scss
libs/scss-entry/src/modules/elements/buttons/_generator.scss
libs/scss-entry/src/modules/typography/_fonts.scss

SCSS Entry font-family mixin

---

libs/scss-entry/src/modules/typography/_fonts.scss

SCSS Entry 

---

libs/entry-components/search-filter/entry-search-filter.component.html

https://enigmatry.atlassian.net/browse/BP-713

BP-713: Adding button class in Search filter

---

libs/entry-components/styles/_generator.scss
libs/entry-components/styles/modules/_default-theme.scss
libs/entry-components/styles/modules/components/dialogs/_generator.scss
libs/entry-components/styles/modules/components/inputs/_generator.scss
libs/entry-components/styles/modules/components/tables/_cells.scss
libs/entry-components/styles/partials/generator-test.scss

Inputs can now have configurable background color. Cell padding on tables are now configurable through theming.

Theme findings fix

---

apps/demo-app/src/app/examples/form/form-example.module.ts
apps/demo-app/src/app/examples/form/rich-text/rich-text-example.component.html
apps/demo-app/src/app/examples/form/rich-text/rich-text-example.component.md
apps/demo-app/src/app/examples/form/rich-text/rich-text-example.component.ts
apps/demo-app/src/app/features/form/form-documentation.component.html
libs/entry-form/ckeditor/formly-ckeditor.component.ts
libs/entry-form/ckeditor/formly-ckeditor.module.ts
package-lock.json
package.json

* Extend material FieldType in formly ckeditor component
* Add example of rich text field in demo app

BP-751: Error when using rich text editor field -> mat-form-field must contain a MatFormFieldControl

---

libs/entry-components/styles/modules/_default-theme.scss
libs/entry-components/styles/modules/vendors/angular-material/_typography-generator.scss

https://enigmatry.atlassian.net/browse/BP-788

BP-788: Theming: add letter spacing property

---

libs/entry-components/configure-theming.md

Extending documentation with new letter spacing property that is included. Check out the details in this [pull request](https://github.com/enigmatry/entry-angular-building-blocks/commit/b66c29b11bd4b4cc3db9b38404fa8f9b6cab7388).

BP-788: Update documentation with new letter space property

---

libs/entry-components/theming-setup.md

Fix broken links since doc file for theming configuration is renamed.

BP-739: Update broken links on theming setup docs

---

libs/entry-components/styles/_generator.scss
libs/entry-components/styles/modules/_default-theme.scss
libs/entry-components/styles/modules/components/checkboxes/_generator.scss
libs/entry-components/styles/partials/generator-test.scss

https://enigmatry.atlassian.net/browse/BP-954

BP-954: Set color and background for checkboxes

---

libs/entry-components/.stylelintrc.json
libs/entry-components/styles/modules/_default-theme.scss
libs/entry-components/styles/modules/components/buttons/_generator.scss
libs/entry-components/styles/modules/components/buttons/_radio.scss

https://enigmatry.atlassian.net/browse/BP-955

BP-955: Set background color for radio buttons

---

libs/entry-components/table/components/entry-table/entry-table.component.html
libs/entry-components/table/components/entry-table/entry-table.component.ts

BP-763: Hide paginator for tables when there are no results

---

libs/entry-form/date-time-picker/formly-date-time-picker.component.html
libs/entry-form/date-time-picker/formly-date-time-picker.component.ts

BP-1053: Date time picker does not select current date time when no value is set

---

libs/entry-components/styles/modules/_default-theme.scss
libs/entry-components/styles/modules/components/buttons/_radio.scss
libs/entry-components/styles/modules/components/checkboxes/_generator.scss
libs/entry-components/styles/modules/components/tables/_header.scss
libs/entry-components/styles/modules/components/tables/_rows.scss
libs/entry-components/styles/modules/components/toggle/_generator.scss
libs/entry-components/theming-configuration.md

https://enigmatry.atlassian.net/browse/BP-976

BP-976: Update documentation for theming with new properties

---

libs/scss-foundation/tests/layout/grid-core.tests.scss
libs/scss-foundation/tests/layout/grid.tests.scss

Fixed 3 failed tests for scss foundation grid

BP-1062: Scss-foundation: Fixed broken tests for grid

---

angular.json
apps/demo-app/src/styles/partials/core/components/_dialogs.scss
libs/entry-components/package.json
libs/entry-components/styles/modules/components/tables/_rows.scss
libs/entry-components/styles/partials/core/components/date-time-picker/_general.scss
libs/entry-components/styles/partials/core/components/forms/_general.scss
libs/entry-components/styles/partials/core/components/search-filter/_general.scss
libs/entry-components/styles/partials/core/components/tables/_general.scss
package-lock.json
package.json

Remove dependency on scss-foundation and update usages to target libs folder instead.

BP-1042: Remove dependency on scss-foundation

---

libs/entry-components/date-time-picker/date-time-picker.component.ts

Add markAsTouched() when updating form control value from code.

BP-1167: Date time picker doesn't display validation messages. Add markAsTouched(). 

---

apps/demo-app/src/app/app.component.html
apps/demo-app/src/app/examples/dialog/custom/custom-dialog.component.html
libs/entry-components/date-time-picker/date-time-picker.component.html
libs/entry-components/file-input/entry-file-input.component.html
libs/entry-components/table/components/entry-table/entry-table.component.html

https://enigmatry.atlassian.net/browse/BP-1194

BP-1194: As a user, I want the UI to be WCAG 2.1 compliant to ensure accessibility for all users

---

libs/stylelint-config/package-lock.json
package-lock.json

Update package-lock files to fix build errors

BP-1225: Update package-lock files for stylelint-config lib

---

apps/demo-app/src/app/examples/table/table-example/table-example.component.ts
libs/entry-components/styles/partials/core/components/tables/_general.scss
libs/entry-components/table/components/entry-cell-context-menu/entry-cell-context-menu.component.html
libs/entry-components/table/components/entry-cell-context-menu/entry-cell-context-menu.component.ts
libs/entry-components/table/interfaces/context-menu-item.ts

BP-1261: Add support for submenus in entry table

---

apps/demo-app/src/app/examples/search-filter/search-filter/search-filter-example.component.ts
apps/demo-app/src/app/examples/search-filter/search-filter/users.service.ts
apps/demo-app/src/app/examples/table/table-example/table-example.component.ts
apps/demo-app/src/styles/partials/core/components/_search-filter.scss
libs/entry-components/search-filter/autocomplete/autocomplete-search-filter.component.html
libs/entry-components/search-filter/date-time/date-time-search-filter.component.html
libs/entry-components/search-filter/date/date-search-filter.component.html
libs/entry-components/search-filter/entry-search-filter.component.html
libs/entry-components/search-filter/entry-search-filter.component.ts
libs/entry-components/search-filter/entry-search-filter.module.ts
libs/entry-components/search-filter/select/select-search-filter.component.html
libs/entry-components/search-filter/text/text-search-filter.component.html
libs/entry-components/styles/partials/core/components/search-filter/_general.scss

https://enigmatry.atlassian.net/browse/BP-1292

BP-1292: In order to see the errors in the form, change entry-search-filter component to display the form errors  

---

libs/entry-components/dialog/dialogs/entry-dialog.component.ts
libs/entry-components/table/components/entry-table/entry-table.component.html

https://enigmatry.atlassian.net/browse/BP-1336

BP-1336: Unexpected Dialog Reopening on Table Row Key Events in Entry Table

---

azure-pipelines.yml
deploy-demo.yml

- FileTransform@1 task is deprecated
- Update pipeline build number (vso[build.updatebuildnumber])

Update pipeline build number and replace deprecated FileTransform@1 task

---

libs/entry-components/search-filter/select/select-search-filter.component.html
libs/entry-components/search-filter/select/select-search-filter.model.ts

Made "None" option configurable in SelectSearchFilter

---

libs/scss-foundation/src/modules/responsiveness/_breakpoints.scss
libs/scss-foundation/tests/layout/grid-core.tests.scss
libs/scss-foundation/tests/layout/grid.tests.scss

https://enigmatry.atlassian.net/browse/BP-1467

BP-1467: Fix Failing SCSS Unit Tests

---

libs/entry-components/styles/modules/_default-theme.scss
libs/entry-components/styles/modules/components/buttons/_generator.scss
libs/entry-components/styles/modules/components/buttons/_radio.scss
libs/entry-components/styles/modules/components/checkboxes/_generator.scss
libs/entry-components/styles/modules/components/inputs/_generator.scss
libs/entry-components/styles/modules/vendors/angular-material/_generator.scss
libs/entry-components/styles/partials/generator-test.scss
libs/entry-components/theming-configuration.md

https://enigmatry.atlassian.net/browse/BP-1495

Theming Extension – Support for Yessa new Design and Angular Material v19/v20 Updates
